package AseanFoodOrderingSystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author lenovo
 */
public class FormTakeAway extends javax.swing.JFrame {

    /**
     * Creates new form FormTakeAway
     */
    public FormTakeAway() {
        initComponents();
        tampilkanMenuTakeAway();
        aturKomponenKustom();
    }
    private void aturKomponenKustom() {
        // 1. Mengubah nama default tombol menjadi Konfirmasi Order
        jButton1.setText("Konfirmasi Order");
        
        // 2. Mengisi JComboBox dengan pilihan ukuran porsi secara statis (atau bisa dinamis jika mau)
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Small", 
            "Medium", 
            "Large" 
             
        }));
        
        // 3. Membersihkan teks default jTextField agar bersih saat aplikasi dibuka
        jTextField1.setText("");
        jTextField2.setText("");
        
        // 4. Mengubah judul Label Header agar rapi
        jLabel1.setText("MENU TAKE AWAY - ASEAN FOOD");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
    }
   private void tampilkanMenuTakeAway() {
   // 1. Array judul kolom dikurangi menjadi 4 kolom saja (Menghilangkan "Jumlah Beli")
        String[] judulKolom = {"ID Makanan", "Nama Makanan", "Asal Negara", "Harga"};
        
        DefaultTableModel model = new DefaultTableModel(null, judulKolom) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Karena kolom Jumlah Beli sudah tidak ada, buat seluruh cell tabel tidak bisa diedit mengetik manual
                return false;
            }
        };
        
        jTable2.setModel(model);
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        try {
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db_restoran_asean", "root", "");
            java.sql.Statement stmt = conn.createStatement();
            
            // Query hanya mengambil menu porsi Medium bertipe take_away
            String sql = "SELECT m.id_makanan, m.nama_makanan, m.asal_negara, v.harga " +
                         "FROM makanan m " +
                         "JOIN varian_porsi v ON m.id_makanan = v.id_makanan " +
                         "WHERE v.ukuran = 'Medium' AND v.bisa_take_away = 1";
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                String namaMakanan = rs.getString("nama_makanan");
                
                // 2. Data array disesuaikan menjadi 4 parameter saja (Tanpa nilai kuantitas awal '0')
                Object[] data = {
                    rs.getInt("id_makanan"),       // Kolom 0
                    namaMakanan,                    // Kolom 1
                    rs.getString("asal_negara"),   // Kolom 2
                    rs.getDouble("harga")           // Kolom 3
                };
                model.addRow(data);
                
                listModel.addElement(namaMakanan);
            }
            
            jList1.setModel(listModel);
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat menu Take Away: " + e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("rwbfhusdhjbf");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setText("Nama Pelanggan:");

        jTextField1.setText("jTextField1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(0, 198, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  String namaPelanggan = jTextField1.getText().trim();
        int barisTerpilih = jTable2.getSelectedRow();
        String jumlahBeliStr = jTextField2.getText().trim(); // Mengambil input jumlah dari jTextField2
        
        // 1. Validasi Input Nama Pelanggan
        if (namaPelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pelanggan belum diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Validasi Seleksi Menu pada Tabel
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih menu makanan pada tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. Validasi Input Jumlah Beli di jTextField2
        if (jumlahBeliStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah makanan belum diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 4. Mengambil Data dari Baris Tabel (Struktur 4 Kolom)
        String namaMakanan = jTable2.getValueAt(barisTerpilih, 1).toString(); // Kolom indeks 1 (Nama Makanan)
        double hargaSatuan = Double.parseDouble(jTable2.getValueAt(barisTerpilih, 3).toString()); // Kolom indeks 3 (Harga)
        
        // Mengambil pilihan ukuran dari JComboBox
        String ukuranPorsi = jComboBox1.getSelectedItem().toString(); 
        
        try {
            // Mengubah input string jumlah menjadi angka integer
            int jumlahBeli = Integer.parseInt(jumlahBeliStr);
            
            if (jumlahBeli <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah beli minimal harus 1!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Perhitungan total harga transaksi
            double totalHarga = hargaSatuan * jumlahBeli;
            
            // 5. Struktur Output Tampilan Struk Konfirmasi
            String detailNota = "============= STRUK PESANAN =============\n" +
                                "Nama Pelanggan  : " + namaPelanggan + "\n" +
                                "Menu Makanan    : " + namaMakanan + "\n" +
                                "Pilihan Ukuran  : " + ukuranPorsi + "\n" +
                                "Jumlah Porsi    : " + jumlahBeli + " Porsi\n" +
                                "Harga Per Porsi : Rp " + hargaSatuan + "\n" +
                                "---------------------------------------\n" +
                                "Total Pembayaran: Rp " + totalHarga + "\n\n" +
                                "Apakah pesanan ini sudah benar?";
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, detailNota, "Konfirmasi Pemesanan", JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Order Berhasil Diproses!");
                
                // Reset semua Form inputan agar kosong kembali dan siap menerima order baru
                jTextField1.setText("");
                jTextField2.setText(""); // Membersihkan teks jumlah makanan
                jTable2.clearSelection();
            }
            
        } catch (NumberFormatException e) {
            // Menangkap error jika user menginput huruf atau simbol ke dalam jTextField2
            JOptionPane.showMessageDialog(this, "Format input pada kolom 'Jumlah' harus berupa angka!", "Gagal Konfirmasi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTakeAway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
