package AseanFoodOrderingSystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author lenovo
 */
public class FormTakeAway extends javax.swing.JFrame {

    /**
     * Creates new form FormTakeAway
     */
    public FormTakeAway() {
        initComponents();
        tampilkanMenuTakeAway("Small");
        aturKomponenKustom();
        
    }
    private void aturKomponenKustom() {
        // 1. Mengubah nama default tombol menjadi Konfirmasi Order
        jButton1.setText("Konfirmasi Order");
        
        // 2. Mengisi JComboBox dengan pilihan ukuran porsi secara statis (atau bisa dinamis jika mau)
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Small", 
            "Medium", 
            "Large" 
             
        }));
        
        // 3. Membersihkan teks default jTextField agar bersih saat aplikasi dibuka
        jTextField1.setText("");
        jTextField2.setText("");
        
        // 4. Mengubah judul Label Header agar rapi
        jLabel1.setText("MENU TAKE AWAY - ASEAN FOOD");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
    }
    private void tampilkanMenuTakeAway(String ukuran) { // <--- Tambahkan parameter 'String ukuran'
    String[] judulKolom = {"ID Makanan", "Nama Makanan", "Asal Negara", "Harga"};
    
    DefaultTableModel model = new DefaultTableModel(null, judulKolom) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    jTable2.setModel(model);
    DefaultListModel<String> listModel = new DefaultListModel<>();
    
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db_restoran_asean", "root", "");
        
        // Query disesuaikan menggunakan parameter ?
        String sql = "SELECT m.id_makanan, m.nama_makanan, m.asal_negara, v.harga " +
             "FROM makanan m " +
             "JOIN varian_porsi v ON m.id_makanan = v.id_makanan " +
             "WHERE v.ukuran = ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, ukuran); // <--- Memasukkan parameter ukuran
        java.sql.ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            String namaMakanan = rs.getString("nama_makanan");
            Object[] data = {
                rs.getInt("id_makanan"),
                namaMakanan,
                rs.getString("asal_negara"),
                rs.getDouble("harga")
            };
            model.addRow(data);
            listModel.addElement(namaMakanan);
        }
        
        jList1.setModel(listModel);
        rs.close();
        ps.close();
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat menu Take Away: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("rwbfhusdhjbf");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setText("Nama Pelanggan:");

        jTextField1.setText("jTextField1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(0, 198, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addComponent(jButton1)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
String namaPelanggan = jTextField1.getText().trim(); 
    if (namaPelanggan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Pelanggan harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    int barisTerpilih = jTable2.getSelectedRow();
    if (barisTerpilih == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih makanan dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int idMakanan = Integer.parseInt(jTable2.getValueAt(barisTerpilih, 0).toString());
    String namaMakanan = jTable2.getValueAt(barisTerpilih, 1).toString();

  
    String ukuranPorsi = jComboBox1.getSelectedItem().toString();

    
    String strJumlah = jTextField2.getText().trim(); 
    if (strJumlah.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Jumlah porsi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int jumlahBeli = 0;
    try {
        jumlahBeli = Integer.parseInt(strJumlah);
        if (jumlahBeli <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah porsi harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah porsi harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 5. KONEKSI DATABASE & CEK STOK (Aman, Mengambil langsung dari varian_porsi)
    double hargaSatuan = 0;
    int stokTersedia = 0;
    int idVarian = 0;
    int bisaTakeAway = 0; // BERUBAH: Mengubah pengecekan hak akses ke bisa_take_away

    String url = "jdbc:mysql://localhost:3306/db_restoran_asean";
    String user = "root";
    String pass = "";

    // BERUBAH: Memastikan field bisa_take_away yang ditarik, bukan bisa_dine_in
    String sqlCek = "SELECT id_varian, harga, stok, bisa_take_away FROM varian_porsi WHERE id_makanan = ? AND ukuran = ?";
    
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);
         java.sql.PreparedStatement psCek = conn.prepareStatement(sqlCek)) {
        
        psCek.setInt(1, idMakanan);
        psCek.setString(2, ukuranPorsi);
        
        try (java.sql.ResultSet rsCek = psCek.executeQuery()) {
            if (rsCek.next()) {
                idVarian = rsCek.getInt("id_varian");
                hargaSatuan = rsCek.getDouble("harga");
                stokTersedia = rsCek.getInt("stok");
                bisaTakeAway = rsCek.getInt("bisa_take_away");
            } else {
                JOptionPane.showMessageDialog(this, "Varian porsi " + ukuranPorsi + " untuk menu ini tidak ditemukan!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } 
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memeriksa stok ke database:\n" + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (jumlahBeli > stokTersedia) {
        JOptionPane.showMessageDialog(this, "Stok tidak mencukupi! Pembelian maksimal porsi ini adalah: " + stokTersedia + " porsi.", "Stok Habis", JOptionPane.WARNING_MESSAGE);
        return;
    }

   
    double totalHarga = hargaSatuan * jumlahBeli;

   
    String struk = "============== STRUK TAKE AWAY ==============\n" +
                   "Nama Pelanggan  : " + namaPelanggan + "\n" +
                   "Menu Makanan    : " + namaMakanan + "\n" +
                   "Pilihan Ukuran   : " + ukuranPorsi + "\n" +
                   "Jumlah Porsi    : " + jumlahBeli + " Porsi\n" +
                   "Harga Per Porsi : Rp " + hargaSatuan + "\n" +
                   "-------------------------------------------\n" +
                   "Total Pembayaran: Rp " + totalHarga + "\n\n" +
                   "Apakah pesanan Take Away ini sudah benar?";

    int konfirmasi = JOptionPane.showConfirmDialog(this, struk, "Konfirmasi Pemesanan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        String sqlUpdateStok = "UPDATE varian_porsi SET stok = stok - ? WHERE id_varian = ?";
        
        
        String sqlInsertPesanan = "INSERT INTO pesanan (nama_pelanggan, tipe_pesanan, no_meja, id_varian, total_harga_rp) VALUES (?, 'TAKEAWAY', NULL, ?, ?)"; 
        
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass)) {
            conn.setAutoCommit(false); 
            
            try (java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdateStok);
                 java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsertPesanan)) {
                
                psUpdate.setInt(1, jumlahBeli);
                psUpdate.setInt(2, idVarian);
                psUpdate.executeUpdate();
                
                psInsert.setString(1, namaPelanggan);
                psInsert.setInt(2, idVarian);
                psInsert.setInt(3, (int) totalHarga);
                psInsert.executeUpdate();
                
                conn.commit(); 
                JOptionPane.showMessageDialog(this, "Pesanan Take Away berhasil diproses!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
           
                jTextField1.setText("");
                jTextField2.setText("");
                jTable2.clearSelection();
                
           
                tampilkanMenuTakeAway(jComboBox1.getSelectedItem().toString());
                
            } catch (java.sql.SQLException ex) {
                conn.rollback(); 
                throw ex;
            }
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memproses transaksi ke database:\n" + e.getMessage(), "Error Transaksi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String ukuranTerpilih = jComboBox1.getSelectedItem().toString();
        tampilkanMenuTakeAway(ukuranTerpilih);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTakeAway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
