/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AseanFoodOrderingSystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class makanDiSini extends javax.swing.JFrame {
   // Array penampung pesanan di memori latar belakang (Tanpa JList)
    private java.util.ArrayList<Integer> listIdVarian = new java.util.ArrayList<>();
    private java.util.ArrayList<String> listNamaMenuBelanja = new java.util.ArrayList<>();
    private java.util.ArrayList<Integer> listJumlahBeli = new java.util.ArrayList<>();
    private java.util.ArrayList<Double> listSubTotalHarga = new java.util.ArrayList<>();
    private javax.swing.DefaultListModel<String> keranjangListModel = new javax.swing.DefaultListModel<>();
    /**
     * Creates new form makanDiSini
     */
    public makanDiSini() {
        initComponents();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        jTextField1.setText(""); // Kolom Nama Pelanggan
        jTextField2.setText(""); // Kolom Jumlah Porsi
        
        // Jalankan pemuatan data menu pertama kali
        tampilkanMenuBerdasarkanUkuran("Small");
    }
    public void tampilkanMenuBerdasarkanUkuran(String ukuran) {
       String[] judulKolom = {"ID Makanan", "Nama Makanan", "Asal Negara", "Harga"};
        DefaultTableModel model = new DefaultTableModel(null, judulKolom) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        // MENGGUNAKAN jTable1 SESUAI DESAIN KAMU
        jTable1.setModel(model);
        
        try {
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db_restoran_asean", "root", "");
            String sql = "SELECT m.id_makanan, m.nama_makanan, m.asal_negara, v.harga " +
                         "FROM makanan m JOIN varian_porsi v ON m.id_makanan = v.id_makanan " +
                         "WHERE v.ukuran = ? AND v.bisa_dine_in = 1";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ukuran);
            java.sql.ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_makanan"),
                    rs.getString("nama_makanan"),
                    rs.getString("asal_negara"),
                    rs.getDouble("harga")
                });
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat daftar menu Dine In: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnTambahkanKeKeranjang = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Menu");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTambahkanKeKeranjang.setText("Tambahkan Ke Keranjang");
        btnTambahkanKeKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanKeKeranjangActionPerformed(evt);
            }
        });

        jButton3.setText("Konfirmasi Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama:");

        jLabel4.setText("Jumlah Porsi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambahkanKeKeranjang)
                    .addComponent(jButton3))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahkanKeKeranjang)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Ukuran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(105, 105, 105))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String ukuranTerpilih = jComboBox1.getSelectedItem().toString();
        tampilkanMenuBerdasarkanUkuran(ukuranTerpilih);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnTambahkanKeKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanKeKeranjangActionPerformed
        // TODO add your handling code here:
       int barisTerpilih = jTable1.getSelectedRow(); // Menggunakan jTable1
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih makanan dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idMakanan = Integer.parseInt(jTable1.getValueAt(barisTerpilih, 0).toString());
        String namaMakanan = jTable1.getValueAt(barisTerpilih, 1).toString();
        String ukuranPorsi = jComboBox1.getSelectedItem().toString();
        String strJumlah = jTextField2.getText().trim(); // Kolom Jumlah Porsi
        
        if (strJumlah.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah porsi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int jumlahBeli = Integer.parseInt(strJumlah);
            if (jumlahBeli <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah porsi harus lebih dari 0!");
                return;
            }

            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db_restoran_asean", "root", "");
            String sqlCek = "SELECT id_varian, harga, stok FROM varian_porsi WHERE id_makanan = ? AND ukuran = ?";
            java.sql.PreparedStatement psCek = conn.prepareStatement(sqlCek);
            psCek.setInt(1, idMakanan);
            psCek.setString(2, ukuranPorsi);
            java.sql.ResultSet rsCek = psCek.executeQuery();

            if (rsCek.next()) {
                int idVarian = rsCek.getInt("id_varian");
                double hargaSatuan = rsCek.getDouble("harga");
                int stokTersedia = rsCek.getInt("stok");

                if (jumlahBeli > stokTersedia) {
                    JOptionPane.showMessageDialog(this, "Stok tidak mencukupi! Sisa stok hanya: " + stokTersedia + " porsi.");
                    conn.close();
                    return;
                }

                double subTotal = hargaSatuan * jumlahBeli;

                // Disimpan langsung ke memori internal program
                listIdVarian.add(idVarian);
                listNamaMenuBelanja.add(namaMakanan + " (" + ukuranPorsi + ")");
                listJumlahBeli.add(jumlahBeli);
                listSubTotalHarga.add(subTotal);

                // Notifikasi kecil kalau item berhasil disimpan ke memori keranjang
                JOptionPane.showMessageDialog(this, namaMakanan + " (" + ukuranPorsi + ") sebanyak " + jumlahBeli + " porsi berhasil ditambahkan!");

                // Reset field jumlah porsi agar siap input item berikutnya
                jTextField2.setText("");
                jTable1.clearSelection();
            }
            rsCek.close();
            psCek.close();
            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah porsi wajib berupa angka bulat!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahkanKeKeranjangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String namaPelanggan = jTextField1.getText().trim(); 
        if (namaPelanggan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Pelanggan wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (listIdVarian.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang belanja kosong! Silakan tambah menu terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder struk = new StringBuilder();
        struk.append("============== STRUK MAKAN DI SINI ==============\n");
        struk.append("Nama Pelanggan  : ").append(namaPelanggan).append("\n");
        struk.append("-------------------------------------------\n");
        struk.append("Daftar Menu Pesanan:\n");

        double totalAkhir = 0;
        for (int i = 0; i < listIdVarian.size(); i++) {
            struk.append("- ").append(listNamaMenuBelanja.get(i))
                 .append(" x").append(listJumlahBeli.get(i))
                 .append(" = Rp ").append(listSubTotalHarga.get(i)).append("\n");
            totalAkhir += listSubTotalHarga.get(i);
        }

        struk.append("-------------------------------------------\n");
        struk.append("TOTAL PEMBAYARAN : Rp ").append(totalAkhir).append("\n\n");
        struk.append("Apakah semua pesanan Makan Di Sini sudah benar?");

        int konfirmasi = JOptionPane.showConfirmDialog(this, struk.toString(), "Konfirmasi Pembayaran", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db_restoran_asean", "root", "")) {
                conn.setAutoCommit(false); 
                
                String sqlUpdateStok = "UPDATE varian_porsi SET stok = stok - ? WHERE id_varian = ?";
                // TIPE PESANAN DISET JADI 'DINEIN' DAN NO_MEJA DIAWALI DENGAN 0 / DEFAULT SEBELUM DI-BOOKING KASIR
            String sqlInsertPesanan = "INSERT INTO pesanan (nama_pelanggan, tipe_pesanan, no_meja, id_varian, total_harga_rp) VALUES (?, 'DINE', NULL, ?, ?)";
                try (java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdateStok);
                     java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsertPesanan)) {
                    
                    for (int i = 0; i < listIdVarian.size(); i++) {
                        psUpdate.setInt(1, listJumlahBeli.get(i));
                        psUpdate.setInt(2, listIdVarian.get(i));
                        psUpdate.addBatch();
                        
                        psInsert.setString(1, namaPelanggan);
                        psInsert.setInt(2, listIdVarian.get(i));
                        psInsert.setInt(3, listSubTotalHarga.get(i).intValue());
                        psInsert.addBatch();
                    }
                    
                    psUpdate.executeBatch();
                    psInsert.executeBatch();
                    conn.commit(); 
                    
                    JOptionPane.showMessageDialog(this, "Sukses! Pesanan Makan Di Sini berhasil disimpan.");
                    
                    jTextField1.setText("");
                    jTextField2.setText("");
                    listIdVarian.clear();
                    listNamaMenuBelanja.clear();
                    listJumlahBeli.clear();
                    listSubTotalHarga.clear();
                    keranjangListModel.clear();
                    
                    
                    tampilkanMenuBerdasarkanUkuran(jComboBox1.getSelectedItem().toString());
                    
                } catch (java.sql.SQLException ex) {
                    conn.rollback();
                    throw ex;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memproses ke database: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new MenuUtama().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makanDiSini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makanDiSini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makanDiSini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makanDiSini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makanDiSini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahkanKeKeranjang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
